Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provision "shell", inline: <<-SHELL

  SHELL
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"

    # for macos:
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
end
